### ISSUE TITLE
Error when trying to convert click command to cwl

### ISSUE THREAD

**Issue by jvdzwaan** [common-workflow-language/gxargparse#17]
I'd like to convert click commands to cwl command line tools. After installing `gxargparse` I get an error if I run the command with or without `--generate_cwl_tool`:

```
> python -m nlppln.replace_ner --generate_cwl_tool
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jvdzwaan/code/nlppln/nlppln/replace_ner.py", line 2, in <module>
    import click
  File "/home/jvdzwaan/code/gxargparse/click/__init__.py", line 20, in <module>
    setattr(__selfmodule__, x, getattr(click, x))
AttributeError: module 'random_name_1' has no attribute 'cwlt'

> python -m nlppln.replace_ner
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jvdzwaan/code/nlppln/nlppln/replace_ner.py", line 2, in <module>
    import click
  File "/home/jvdzwaan/code/gxargparse/click/__init__.py", line 20, in <module>
    setattr(__selfmodule__, x, getattr(click, x))
AttributeError: module 'random_name_1' has no attribute 'cwlt'
(cwl3) jvdzwaan@ESLT0062:~/code/gxargparse$ 
```

The error also occurs in Python 2.7:

```
> python -m nlppln.replace_ner --generate_cwl_tool
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jvdzwaan/code/nlppln/nlppln/replace_ner.py", line 2, in <module>
    import click
  File "click/__init__.py", line 20, in <module>
    setattr(__selfmodule__, x, getattr(click, x))
AttributeError: 'module' object has no attribute 'cwlt'

> python -m nlppln.replace_ner
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jvdzwaan/code/nlppln/nlppln/replace_ner.py", line 2, in <module>
    import click
  File "click/__init__.py", line 20, in <module>
    setattr(__selfmodule__, x, getattr(click, x))
AttributeError: 'module' object has no attribute 'cwlt'
```

In both instances `gxargparse_check_path` gives `Ready to go!`

**Comment by anton-khodak** [comment]
@jvdzwaan thank you for reporting! I'll try to fix it ASAP

**Comment by mr-c** [comment]
@jvdzwaan Hello from CWL London week! I wasn't able to reproduce the error, but @anton-khodak was. We will try again tomorrow.

**Comment by anton-khodak** [comment]
@jvdzwaan I have reproduced your error, I can not explain why, but if you deactivate your virtual environment, activate it again and move out of the directory with the virtualenv (i.e. `cd ~`), things start to work. Check it on your computer

**Comment by jvdzwaan** [comment]
@anton-khodak Actually, now it just works (I did reinstall my laptop in the mean time, so that may have something to do with it). Thank you for looking into this!
